### ISSUE TITLE
Consider using hashed+salted passwords and constant time comparison

### ISSUE THREAD

**Issue by lmars** [ably/asset-tracking-backend-demo#6]
Whilst this is only demo code, given there is a chance customers might build their own solutions from this code, I think we should follow security best practices.

Ideally, the passwords would be stored hashed and salted, and the comparison of the user supplied password with the stored one would take a constant amount of time to avoid timing attacks. This could be achieved by using the [bcrypt npm package](https://www.npmjs.com/package/bcrypt).

Alternatively, we could just not manage username and passwords at all and use OIDC to delegate authentication to an IdP (e.g. Google/Facebook/Okta/Auth0 etc.)

┆Issue is synchronized with this [Jira Uncategorised](https://ably.atlassian.net/browse/SDK-2430) by [Unito](https://www.unito.io)

**Comment by QuintinWillison** [comment]
Thanks and totally agreed. 😁 

I think, to refrain from expanding scope too much and introducing non-critical-path extras to the codebase, I will go with your first suggestion of hashing and salting. At least that shows care for best practices in more than just the core goals of the demo, in an area that's known to be skipped/botched regularly in many production systems.

I will, however, also add some commentary to the readme under this issue to suggest that the ideal scenario would be to use OIDC... it's ok to leave some exercises up to the reader, and as stated above it keeps the code focussed and perhaps still relatively easy to follow.

**Comment by lmars** [comment]
Sounds good to me 🙂

**Comment by QuintinWillison** [comment]
@owenpearson The main challenge I see with this change is how we make it easy enough for the wider demo development and QA team to create new users, as I think it's important that they can self-service on that (they all have access to the Firebase account so can mutate the Firestore).

Evolving on the work done in https://github.com/ably/asset-tracking-backend-demo/pull/5
